#Use NGSadmix to infer admixture proportions from genotype likelihood file generated by angsd

#!/bin/bash
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=5:mem=40gb

DIR=/rds/general/user/rz520/home/project/data
BASEDIR=/rds/general/user/rz520/home/project
NGSadmix=/rds/general/user/rz520/home/workshop/Software/NGSadmix

echo "realSFS start"
$NGSadmix -likes $BASEDIR/results/ALL_ANGSD_PCA.beagle.gz -K 2 -o $BASEDIR/results/ALL_ANGSD_PCA_ngsAdmix_K2_out

echo "finish"
